{"run_number": "1713684251318523", "step_name": "prepare_dataset", "task_id": "2", "attempt_id": 0, "name": "_exception", "content_type": "gzip+pickle-v2", "type": "metaflow.artifact", "sha": "073e92ce48e545c2a93dcb9c4879d29bc6fa8fbc", "ds_type": "local", "location": ":root:/home/shashwat/Desktop/Newest Microservice/.metaflow", "flow_id": "DataFlow", "user_name": "shashwat", "tags": [], "system_tags": ["user:shashwat", "metaflow_version:2.11.10", "runtime:dev", "python_version:3.11.7"], "ts_epoch": 1713684251813}